version: '3.9'
services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
